name: deploy to Fly (dev)

on:
  push:
    branches: [ dev ]

concurrency:
  group: fly-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1

      # (optional) quick debug so you can see which Fly account the token belongs to
      - name: fly whoami
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth whoami

      - name: Deploy (fly.test.toml)
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}   # <-- your repo secret
        run: flyctl deploy --config ./fly.test.toml --remote-only
